name: genlocale
on: [ push ]
jobs:
  golangci:
    name: genlocale
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Extract i18n
        run: python3 extract_locale.py

      - name: Sync i18n to zh_CN.json
        python3 "./locale/locale_diff.py"

      - name: Commit back
        if: ${{ !github.head_ref }}
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "🎨 Update i18n(更新本地化)"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main